# Generated by Django 3.2.3 on 2021-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('file_obj', models.FileField(upload_to='')),
                ('file_name', models.CharField(editable=False, max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField()),
                ('done_at', models.DateTimeField()),
            ],
        ),
    ]
