# Generated by Django 3.2.3 on 2021-05-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
