# Generated by Django 3.2.3 on 2021-05-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='done_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='downloaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
