# Generated by Django 3.2.3 on 2021-05-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210518_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
