# Generated by Django 3.2.3 on 2021-05-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imagemodel_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='seconds',
            field=models.IntegerField(null=True),
        ),
    ]
